### ISSUE TITLE
Question - How to contribute 

### ISSUE THREAD

**Issue by clement-brodu** [spazzymoto/ablduck#4]
Hello,

I would like to make some improvements to the ablduck template.

But, I have a question : How can I build your project to generate my own template ?

For now, I made some customization in files I found in ablduck output directory, but I would like to shared my changed.

You can see the result here : https://clement-brodu.github.io/OEdoc-sample
_I made some change in PCT to improve some comments, you can see my PR in PCT project._

Here are my changed : 
- customize some icons 
- adding a js file to define [hyperlink to other documentation](https://clement-brodu.github.io/OEdoc-sample/#!/class/property.PropertyType). 
_(It could be a good idea if PCT user can customize the link generation)._

You can see all my change in this [commit](https://github.com/clement-brodu/OEdoc-sample/commit/39283a8660648a3cf3a45eaf6fc70acd040ad1bf)

Thanks you,

**Comment by spazzymoto** [comment]
Hey @clement-brodu,

It has been a while since i have looked at this project as i was no longer working with OpenEdge, But as of this year i am back to OpenEdge.

I will take some time to remind myself how to build it this evening and will update the readme.

Rob

**Comment by spazzymoto** [comment]
I have updated the readme and uploaded the Sencha CMD installers, in case Sencha decides to remove the install links. Its quite an old version, i need to look at upgrading it.

**Comment by clement-brodu** [comment]
Thank you, I will try it 👍
