### ISSUE TITLE
Tag {@link} doesn't work

### ISSUE THREAD

**Issue by clement-brodu** [spazzymoto/ablduck#8]
Hi,

I would like to use the tag `{@link}` that is documented but it doesn't work in last PCT version

> {@link}
> You can use the link tag to link to any other class in your preprocessed codebase.
> ```
>  {@link  class  (linkText optional)}  
>  {@link  class-method-methodName (linkText optional)}  
>  {@link  class-property-PropertyName (linkText optional)}  
>  {@link  class-event-EventName (linkText optional)}  
> ```

I made some tests with several PCT version and it seems that it work on PCT 209 but since PCT 213, it doesn't work anymore.

I can help to fix that, but I'm not a Javascript expert. 

Do you know which part of the code is use for this feature ? 

Thank you :)

**Comment by spazzymoto** [comment]
Hi, 
Sorry about that I'll take a look and see where it's going wrong, it may be in the java classes in PCT.

**Comment by clement-brodu** [comment]
Hi ! 
Do you have any news about this ?

**Comment by spazzymoto** [comment]
Hey,
Sorry work got crazy and it slipped my mind, apologies. I have resolved it and will open a PR in PCT shortly. Could you test with this version of PCT if you like to confirm its working for you.
[PCT.zip](https://github.com/spazzymoto/ablduck/files/6204925/PCT.zip)

**Comment by gquerret** [comment]
Pull requests are automatically built, yours can be seen here: https://ci.rssw.eu/job/PCT/view/change-requests/job/PR-447/
@clement-brodu Can you test the JAR file from this location ?

**Comment by clement-brodu** [comment]
It's ok for me 👍 

https://clement-brodu.github.io/OEdoc-sample/#!/class/Hello.Son

I didn't try everything, but those case works : 
```
        {@link  Hello.Father see father}  
        {@link  Hello.Father-method-HelloWorld see father HelloHorld}  
        {@link  property.PropertyComment-property-property2 see PropertyComment property2}
```

Thanks for the fix !

**Comment by gquerret** [comment]
Merged in PCT master branch

**Comment by gquerret** [comment]
Anyway, are you back in the OpenEdge world ? ;-)

**Comment by spazzymoto** [comment]
Thanks for the merge :).
I am back at MIP again so back to the OpenEdge world. I've been meaning to try get back on the OE slack to chat to you about some thoughts i had on incremental compiles. I will see if i can do it this week. Hope you have been keeping well.
